packages:
  - 'frontend'
allowBuilds:
  esbuild: false

minimumReleaseAge: 0

overrides:
  brace-expansion: "5.0.8"
  react-router: "^8.3.0"
  react-router-dom: "^7.18.1"
  vite: "^6.4.3"
  esbuild: ">=0.25.0"
