# Generated by Django 4.2.30 on 2026-08-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_completed_onboarding',
            field=models.BooleanField(default=False, help_text='Whether the user has completed the onboarding wizard'),
        ),
    ]
